feat: eim の実行結果に基づいて synth の実行を制御する
acompany-develop/Gramine-EIM-Synth-DEMO pull request #21
Opened 2024-11-28 04:27 UTC by yeighta

## 概要
-

2024-11-28 07:14 UTC, sakamoto-souta requested changes

2024-11-28 07:14 UTC, sakamoto-souta commented on demo_docker/docker-compose.yaml
>          while [ ! -f /sync/firm_demo0_eim_done ] || [ ! -f /sync/firm_demo1_eim_done ]; do sleep 1; done && \
`/sync/firm_demo1_eim_failed` の存在検出が最初に一回しか行われない場合、matching よりも先にこちらが処理される場合に検出に失敗しそうです。
例えば以下のように出来るかなと思いますが、シェルは不慣れなのでもっといい書き方があればそちらを採用してください。
```suggestion
        while [ ! -f /sync/firm_demo0_eim_done ] || [ ! -f /sync/firm_demo1_eim_done ]; do \
            if [ -f /sync/firm_demo1_eim_failed ]; then exit 1; fi && \
            sleep 1; \
        done && \
```

2024-11-29 08:15 UTC, yeighta commented on demo_docker/docker-compose.yaml
>          while [ ! -f /sync/firm_demo0_eim_done ] || [ ! -f /sync/firm_demo1_eim_done ]; do sleep 1; done && \
こちら良さそうだったのでコミットしています！

2024-11-29 08:18 UTC, sakamoto-souta approved these changes

2024-11-29 08:37 UTC, merged